plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'dagger.hilt.android.plugin'
    id 'com.github.ben-manes.versions' version "0.51.0"
}

android {
    namespace "com.project.noticeme.common.utils"
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        versionCode libs.versions.versionCode.get().toInteger()
        versionName libs.versions.versionName.get()
    }
    
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    
    kotlinOptions {
        jvmTarget = "17"
    }
    
    lintOptions {
        abortOnError false
        disable 'UnsafeExperimentalUsageError', 'UnsafeExperimentalUsageWarning', 'ContentDescription'
    }
    
    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    // Kotlin
    implementation libs.kotlin.stdlib
    
    // AndroidX Core
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx

    // Startup
    implementation libs.androidx.startup.runtime

    // Networking
    implementation libs.gson
    implementation libs.okhttp3.okhttp

    // Dependency Injection
    implementation libs.hilt.android
    ksp libs.hilt.android.compiler

    // Debug
    implementation libs.timber
    implementation libs.stetho
    implementation libs.stetho.okhttp3
}

def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

dependencyUpdates {
    rejectVersionIf {
        isNonStable(it.candidate.version)
    }
}
